stages:
  # Source: PDF 5, Page 17 (Hyperparameter Tuning stage)
  hp_tune:
    cmd: python hp_tuning.py
    deps:
      - hp_config.json
      - hp_tuning.py
      - weather.csv
    outs:
      - rfc_best_params.json:
          cache: false
