name: HP Tuning
on: [push]

permissions:
  # Source: PDF 5, Page 25 and 49 (Setup workflow permissions)
  contents: write
  pull-requests: write

jobs:
  hp_tune_and_publish_report:
    runs-on: ubuntu-latest




    # --- THIS IS THE CRITICAL PART ---
    # This tells GitHub to look inside the 'set5' folder
    # 1. Point to the correct folder
    defaults:
      run:
        working-directory: ./cicd_learning_course/set5
    # ----------------------------------



    
    # Source: PDF 5, Page 24 (Setting conditionals for branch name)
    if: startsWith(github.ref, 'refs/heads/hp_tune/')
    steps:
      - uses: actions/checkout@v3
      
      # Source: PDF 5, Page 4 (Setup DVC)
      - uses: iterative/setup-dvc@v1
      # Source: PDF 5, Page 10 (Setup CML)
      - uses: iterative/setup-cml@v1
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Source: PDF 5, Page 24 (Running logic)
      - name: Run HP Tuning
        run: |
          dvc init --no-scm -f
          dvc repro -f hp_tune

      # Source: PDF 5, Page 28 (Creating a training PR)
      - name: Create training branch
        env:
          # Source: PDF 5, Page 28 (Using Secrets)
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export BRANCH_NAME=train/$(git rev-parse --short "${{ github.sha }}")
          
          # Source: PDF 5, Page 28 (CML Command)
          cml pr create \
            --message "Hyperparameter tuning result" \
            --branch $BRANCH_NAME \
            --target-branch main \
            rfc_best_params.json

