name: HP Tuning
on: [push]

permissions:
  contents: write
  pull-requests: write

jobs:
  hp_tune_and_publish_report:
    runs-on: ubuntu-latest

    # --- FIX IS HERE ---
    # We use 'github.ref' and 'refs/heads/' to correctly detect the branch name on push
    if: startsWith(github.ref, 'refs/heads/hp_tune/')

    defaults:
      run:
        working-directory: ./cicd_learning_course/set5

    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
      - uses: iterative/setup-cml@v1
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run HP Tuning
        run: |
          dvc init --no-scm -f
          dvc repro -f hp_tune

      - name: Create training branch
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export BRANCH_NAME=train/$(git rev-parse --short "${{ github.sha }}")
          
          cml pr create \
            --message "Hyperparameter tuning result" \
            --branch $BRANCH_NAME \
            --target-branch main \
            rfc_best_params.json
