name: Train Model
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest




    # ADD THIS SECTION
    defaults:
      run:
        working-directory: ./cicd_learning_course/set2


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      # Source: PDF 3, Page 10 (CML Commands / Training Steps)
      - name: Train model
        run: |
          pip install -r requirements.txt
          python3 train.py
